name: Build and Push

on:
  push:
    branches:
      - main
      - 'v*'
      - 'releases/**'
  workflow_dispatch:

jobs:
  build-and-push-image:
    # Name of the job which will be shown on the web console
    name: Build and Push Docker Image
    # Use a list of labels to determine which runner the workflow will run on
    runs-on:
      - ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE on runner, so your workflow can access it
      - uses: actions/checkout@v2

      - name: Login Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}


       # To build and push Docker image with Buildx with full support of the features provided by Moby BuildKit builder toolkit
      - name: Build and push
        #id: A unique identifier for the step. You can use the id to reference the step in contexts
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # push: Push the build result to registry, default: false
          push: true
          tags: "sh777/vistual-chatgpt:v1"
      #    # Do not use cache when building the image
          no-cache: true
          # secrets: Set the variables which will be delivered to Dockerfile to build Java


 